grammar variables;
fragment DIGIT
    : [1-9]
    | ZERO;
fragment ZERO
    : '0';
fragment LOW_CHAR
    : [a-z];
fragment HIGH_CHAR
    : [A-Z];
fragment CHAR
    : HIGH_CHAR
    | LOW_CHAR;
fragment STRING
    : CHAR*;
fragment INTEGER
    : DIGIT*
    | ZERO;
fragment FLOAT
    : ZERO? '.' DIGIT*
    | INTEGER;
fragment TRUE
    : 'True'
    | '1';
fragment FALSE
    : 'False'
    | '0';
fragment BOOLEAN
    : TRUE
    | FALSE;
